SELECT  
  NVL(TDCD.TDCDFACTURA, WCD.WCDFACTURA)"SHIPMENT_NO", '' "CARRIER", '' "PLANNED_SHIPDATE", to_date(WCD.DATE_CREATED) "SHIP_DATE", '' "PLANNED_DELIVERY_DATE", INITCAP(DIS.DISNOM) "ORIGIN", InitCap(DISADRESSE1 || ' ' || ' ' || DISNUMEXT || '  ' || DISNUMINT || '  ' ||DISADRESSE2 || DECODE(DISCODEPOSTAL ,NULL,NULL, ' C.P. ' || DISCODEPOSTAL)) "ORIGIN_ADDRESS",  
  INITCAP(CIU_ORI.VILNOM || ' ('|| EST_ORI.ESTNOMBRE || ')')"ORIGIN_CITY", INITCAP(CCL.CCL_NOMBRE || ' ' || NVL(DIE.DIE_A_ATENCION_DE, DIE.DIENOMBRE)) "DESTINATION", InitCap( DIEADRESSE1|| ' ' || ' ' || DIENUMEXT || '  ' || DIENUMINT || '  ' ||DIEADRESSE2 || DECODE(DIECODEPOSTAL,NULL,NULL, ' C.P. ' || DIECODEPOSTAL)) "DESTINATION_ADDRESS", 
  INITCAP(CIU_DEST.VILNOM || ' ('|| EST_DEST.ESTNOMBRE || ')') DESTINATION_CITY, 'Road' "MODE_", WCD.WCD_FIRMA "SHIPMENT_LINE#", to_char(TO_DATE(WCD.DATE_CREATED), 'mm/dd/yyyy hh24:mi') "CREATION_DATE"
  FROM  
  WCROSS_DOCK WCD, EDIRECCIONES_ENTREGA DIE, ECLIENT_CLIENTE CCL, EDISTRIBUTEUR DIS, ECIUDADES CIU_ORI, EESTADOS EST_ORI, ECIUDADES CIU_DEST, EESTADOS EST_DEST, ETRANS_DETALLE_CROSS_DOCK TDCD, ETRANSFERENCIA_TRADING TRA, ETRANS_ENTRADA TAE  
  WHERE  
  TRUNC(WCD.DATE_CREATED) BETWEEN TRUNC(sysdate -1) AND TRUNC(sysdate -1) AND WCD_CLICLEF in(20501,20502) AND NOT NVL(TDCD.TDCDFACTURA, WCD.WCDFACTURA) LIKE '%PRUEBA%' AND NOT NVL(TDCD.TDCDFACTURA, WCD.WCDFACTURA) LIKE '%SENSORES%'
  AND NOT NVL(TDCD.TDCDFACTURA, WCD.WCDFACTURA) LIKE '%TARIMAS%' AND DISCLEF = WCD.WCD_DISCLEF AND DIECLAVE = NVL(NVL(TDCD_DIECLAVE_ENT, TDCD_DIECLAVE), WCD_DIECLAVE_ENTREGA) AND CCLCLAVE = NVL(TDCD_CCLCLAVE, WCD.WCD_CCLCLAVE)  
  AND CIU_ORI.VILCLEF = DISVILLE AND EST_ORI.ESTESTADO = CIU_ORI.VIL_ESTESTADO AND CIU_DEST.VILCLEF = DIEVILLE AND EST_DEST.ESTESTADO = CIU_DEST.VIL_ESTESTADO AND TDCDCLAVE(+) = WCD.WCD_TDCDCLAVE AND TDCDSTATUS (+) = '1'  
  AND TRACLAVE(+) = WCD.WCD_TRACLAVE AND TRASTATUS (+) = '1' AND TAE_TRACLAVE(+) = WCD.WCD_TRACLAVE
  UNION
  SELECT
    NVL(TDCD.TDCDFACTURA, WEL.WELFACTURA) "SHIPMENT_NO", '' "CARRIER", '' "PLANNED_SHIPDATE",
    to_date(WEL.DATE_CREATED) "SHIP_DATE", '' "PLANNED_DELIVERY_DATE", INITCAP(DIS.DISNOM)  "ORIGIN",
    INITCAP(DISADRESSE1 || ' ' || ' ' || DISNUMEXT || '  ' || DISNUMINT || '  ' ||DISADRESSE2 || DECODE(DISCODEPOSTAL,NULL,NULL, ' C.P. ' || DISCODEPOSTAL)) "ORIGIN_ADDRESS",
    INITCAP(CIU_ORI.VILNOM || ' ('|| EST_ORI.ESTNOMBRE || ')') "ORIGIN_CITY",
    INITCAP(CCL.CCL_NOMBRE || ' ' || NVL(DIE.DIE_A_ATENCION_DE, DIE.DIENOMBRE)) "DESTINATION",
    INITCAP( DIEADRESSE1|| ' ' || ' ' || DIENUMEXT || '  ' || DIENUMINT || '  ' ||DIEADRESSE2 || DECODE(DIECODEPOSTAL,NULL,NULL, ' C.P. ' || DIECODEPOSTAL)) "DESTINATION_ADDRESS",
    INITCAP(CIU_DEST.VILNOM || ' ('|| EST_DEST.ESTNOMBRE || ')') "DESTINATION_CITY",
    'ROAD' "MODE_", WEL.WEL_FIRMA "SHIPMENT_LINE#", to_char(TO_DATE(WEL.DATE_CREATED), 'mm/dd/yyyy hh24:mi') "CREATION_DATE"
  FROM
    WEB_LTL WEL,
    EDIRECCIONES_ENTREGA DIE,
    ECLIENT_CLIENTE CCL,
    EDISTRIBUTEUR DIS,
    ECIUDADES CIU_ORI,
    EESTADOS EST_ORI,
    ECIUDADES CIU_DEST,
    EESTADOS EST_DEST,
    ETRANS_DETALLE_CROSS_DOCK TDCD,
    ETRANSFERENCIA_TRADING TRA,
    ETRANS_ENTRADA TAE
  WHERE 1=1
    AND TRUNC(WEL.DATE_CREATED) BETWEEN TRUNC(SYSDATE -1) AND TRUNC(SYSDATE -1)
    AND WEL_CLICLEF IN(20501,20502,23488,23489)

    AND NOT NVL(TDCD.TDCDFACTURA, WEL.WELFACTURA) LIKE '%PRUEBA%'
    AND NOT NVL(TDCD.TDCDFACTURA, WEL.WELFACTURA) LIKE '%SENSORES%'
    AND NOT NVL(TDCD.TDCDFACTURA, WEL.WELFACTURA) LIKE '%TARIMAS%'
    AND DISCLEF = WEL.WEL_DISCLEF
    AND DIECLAVE = NVL(NVL(TDCD_DIECLAVE_ENT, TDCD_DIECLAVE), WEL_DIECLAVE)
    AND CCLCLAVE = NVL(TDCD_CCLCLAVE, WEL.WEL_CCLCLAVE)
    AND CIU_ORI.VILCLEF = DISVILLE
    AND EST_ORI.ESTESTADO = CIU_ORI.VIL_ESTESTADO
    AND CIU_DEST.VILCLEF = DIEVILLE
    AND EST_DEST.ESTESTADO = CIU_DEST.VIL_ESTESTADO
    AND TDCDCLAVE(+) = WEL.WEL_TDCDCLAVE
    AND TDCDSTATUS (+) = '1'
    AND TRACLAVE(+) = WEL.WEL_TRACLAVE
    AND TRASTATUS (+) = '1'
    AND TAE_TRACLAVE(+) = WEL.WEL_TRACLAVE
