/*	*	*	*	*	*	*	*
 *	Reportes Bajo Demanda	*
 *	*	*	*	*	*	*	*/
SELECT   RDR.ID_CRON "IdCron"
        ,RDR.ID_REPORTE "IdRep"
        ,RDR.NOMBRE "NombreReporte"
        ,RC.PRIORIDAD "Prioridad"
        ,TO_CHAR(NVL(RDR.DATE_MODIFIED,RDR.DATE_CREATED),'DD/MM/YYYY HH24:MI:SS') "Fecha"
        ,TO_CHAR(RC.FECHA_ULTIMA_EJECUCION,'DD/MM/YYYY HH24:MI:SS') "UltimaEjecucion"
        ,RC.STATUS "Activo"
        ,RC.EN_EJECUCION "EnProceso"
        ,RC.MINUTOS "Minutos"
        ,RC.HORAS "Horas"
        ,RC.DIAS "Dias"
        ,RC.MES "Mes"
        ,RC.DIA_SEMANA "DiaSemana"
        ,1 "BajoDemanda"
        ,TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') "SysDate"
FROM SC_RS_DIST.TB_REP_DETALLE_REPORTE RDR
    INNER JOIN SC_RS_DIST.TB_REP_CHRON RC ON RDR.ID_CRON = RC.ID_CRON
WHERE   RC.EN_EJECUCION = 0
    AND RC.STATUS = 1
    AND RC.MINUTOS IS NULL
    AND RC.HORAS IS NULL
    AND RC.DIAS IS NULL
    AND RC.MES IS NULL
    AND RC.DIA_SEMANA IS NULL
    AND TRUNC(NVL(RDR.DATE_MODIFIED,RDR.DATE_CREATED)) >= TRUNC(SYSDATE-1)
UNION
/*	*	*	*	*	*	*	*
 *	Reportes Programados	*
 *	*	*	*	*	*	*	*/
/* SIN UN DIA ESPECIFICO (UNICAMENTE HORAS Y/O MINUTOS) */
    SELECT   RDR.ID_CRON "IdCron"
            ,RDR.ID_REPORTE "IdRep"
            ,RDR.NOMBRE "NombreReporte"
            ,RC.PRIORIDAD "Prioridad"
            ,TO_CHAR(NVL(RDR.DATE_MODIFIED,RDR.DATE_CREATED),'DD/MM/YYYY HH24:MI:SS') "Fecha"
            ,TO_CHAR(RC.FECHA_ULTIMA_EJECUCION,'DD/MM/YYYY HH24:MI:SS') "UltimaEjecucion"
            ,RC.STATUS "Activo"
            ,RC.EN_EJECUCION "EnProceso"
            ,RC.MINUTOS "Minutos"
            ,RC.HORAS "Horas"
            ,RC.DIAS "Dias"
            ,RC.MES "Mes"
            ,RC.DIA_SEMANA "DiaSemana"
            ,0 "BajoDemanda"
            ,TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') "SysDate"
    FROM SC_RS_DIST.TB_REP_DETALLE_REPORTE RDR
        INNER JOIN SC_RS_DIST.TB_REP_CHRON RC ON RDR.ID_CRON = RC.ID_CRON
    WHERE   NVL(RC.EN_EJECUCION,0) = 0
        AND RC.STATUS = 1
        AND (RC.DIAS IS NULL AND RC.MES IS NULL AND RC.DIA_SEMANA IS NULL)
        AND (RC.MINUTOS IS NOT NULL OR RC.HORAS IS NOT NULL)
        AND (
                TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MI'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT(NVL(RC.MINUTOS,TO_CHAR(SYSDATE,'MI'))))
                OR
                TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MI'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT(NVL(RC.MINUTOS,TO_CHAR(SYSDATE,'MI'))))
            )
        AND (
                TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'HH24'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT(NVL(RC.HORAS,TO_CHAR(SYSDATE,'HH24'))))
                OR
                TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'HH24'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT(NVL(RC.HORAS,TO_CHAR(SYSDATE,'HH24'))))
            )
UNION
/* CON UN DIA DE LA SEMANA ESPECIFICO CONFIGURADO */
    SELECT   RDR.ID_CRON "IdCron"
            ,RDR.ID_REPORTE "IdRep"
            ,RDR.NOMBRE "NombreReporte"
            ,RC.PRIORIDAD "Prioridad"
            ,TO_CHAR(NVL(RDR.DATE_MODIFIED,RDR.DATE_CREATED),'DD/MM/YYYY HH24:MI:SS') "Fecha"
            ,TO_CHAR(RC.FECHA_ULTIMA_EJECUCION,'DD/MM/YYYY HH24:MI:SS') "UltimaEjecucion"
            ,RC.STATUS "Activo"
            ,RC.EN_EJECUCION "EnProceso"
            ,RC.MINUTOS "Minutos"
            ,RC.HORAS "Horas"
            ,RC.DIAS "Dias"
            ,RC.MES "Mes"
            ,RC.DIA_SEMANA "DiaSemana"
            ,0 "BajoDemanda"
            ,TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') "SysDate"
    FROM SC_RS_DIST.TB_REP_DETALLE_REPORTE RDR
        INNER JOIN SC_RS_DIST.TB_REP_CHRON RC ON RDR.ID_CRON = RC.ID_CRON
    WHERE   NVL(RC.EN_EJECUCION,0) = 0
        AND RC.STATUS = 1
        AND RC.DIA_SEMANA IS NOT NULL
        AND RC.DIA_SEMANA = TO_CHAR(SYSDATE, 'D')
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MM'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT((NVL(RC.MES,TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MM')))))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'DD'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT((NVL(RC.DIAS,TO_CHAR(SYSDATE,'DD')))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'HH24'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT((NVL(RC.HORAS,TO_CHAR(SYSDATE,'HH24')))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MI'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT((NVL(RC.MINUTOS,TO_CHAR(SYSDATE,'MI')))))
UNION
/* CON UN RANGO DE D�AS A LA SEMANA CONFIGURADO */
    SELECT   RDR.ID_CRON "IdCron"
            ,RDR.ID_REPORTE "IdRep"
            ,RDR.NOMBRE "NombreReporte"
            ,RC.PRIORIDAD "Prioridad"
            ,TO_CHAR(NVL(RDR.DATE_MODIFIED,RDR.DATE_CREATED),'DD/MM/YYYY HH24:MI:SS') "Fecha"
            ,TO_CHAR(RC.FECHA_ULTIMA_EJECUCION,'DD/MM/YYYY HH24:MI:SS') "UltimaEjecucion"
            ,RC.STATUS "Activo"
            ,RC.EN_EJECUCION "EnProceso"
            ,RC.MINUTOS "Minutos"
            ,RC.HORAS "Horas"
            ,RC.DIAS "Dias"
            ,RC.MES "Mes"
            ,RC.DIA_SEMANA "DiaSemana"
            ,0 "BajoDemanda"
            ,TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') "SysDate"
    FROM SC_RS_DIST.TB_REP_DETALLE_REPORTE RDR
        INNER JOIN SC_RS_DIST.TB_REP_CHRON RC ON RDR.ID_CRON = RC.ID_CRON
    WHERE   NVL(RC.EN_EJECUCION,0) = 0
        AND RC.STATUS = 1
        AND RC.DIA_SEMANA IS NOT NULL
        AND TO_CHAR(SYSDATE, 'D') BETWEEN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT(RC.DIA_SEMANA,'-') WHERE ROWNUM=1) AND (REPLACE(RC.DIA_SEMANA,(SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT(RC.DIA_SEMANA,'-') WHERE ROWNUM=1)||'-',''))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MM'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT((NVL(RC.MES,TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MM')))))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'DD'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT((NVL(RC.DIAS,TO_CHAR(SYSDATE,'DD')))))
        AND (
                TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'HH24'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT(NVL(RC.HORAS,TO_CHAR(SYSDATE,'HH24'))))
                OR
                TO_CHAR(SYSDATE, 'HH24') BETWEEN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT(RC.HORAS,'-') WHERE ROWNUM=1) AND (REPLACE(RC.HORAS,(SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT(RC.HORAS,'-') WHERE ROWNUM=1)||'-',''))
            )
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MI'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT((NVL(RC.MINUTOS,TO_CHAR(SYSDATE,'MI')))))
UNION
/* CON ALGUNOS D�AS DE LA SEMANA CONFIGURADOS */
    SELECT   RDR.ID_CRON "IdCron"
            ,RDR.ID_REPORTE "IdRep"
            ,RDR.NOMBRE "NombreReporte"
            ,RC.PRIORIDAD "Prioridad"
            ,TO_CHAR(NVL(RDR.DATE_MODIFIED,RDR.DATE_CREATED),'DD/MM/YYYY HH24:MI:SS') "Fecha"
            ,TO_CHAR(RC.FECHA_ULTIMA_EJECUCION,'DD/MM/YYYY HH24:MI:SS') "UltimaEjecucion"
            ,RC.STATUS "Activo"
            ,RC.EN_EJECUCION "EnProceso"
            ,RC.MINUTOS "Minutos"
            ,RC.HORAS "Horas"
            ,RC.DIAS "Dias"
            ,RC.MES "Mes"
            ,RC.DIA_SEMANA "DiaSemana"
            ,0 "BajoDemanda"
            ,TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') "SysDate"
    FROM SC_RS_DIST.TB_REP_DETALLE_REPORTE RDR
        INNER JOIN SC_RS_DIST.TB_REP_CHRON RC ON RDR.ID_CRON = RC.ID_CRON
    WHERE   NVL(RC.EN_EJECUCION,0) = 0
        AND RC.STATUS = 1
        AND RC.DIA_SEMANA IS NOT NULL
        AND RC.DIA_SEMANA LIKE '%,%'
        AND (RC.DIA_SEMANA) LIKE '%' || TO_CHAR(SYSDATE, 'D') || '%'
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MM'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT(NVL(RC.MES,TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MM'))))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'DD'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT(NVL(RC.DIAS,TO_CHAR(SYSDATE,'DD'))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'HH24'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT(NVL(RC.HORAS,TO_CHAR(SYSDATE,'HH24'))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MI'))) IN (SELECT COLUMN_VALUE FROM SC_RS_DIST.SPG_REP_UTL.F_SPLIT(NVL(RC.MINUTOS,TO_CHAR(SYSDATE,'MI'))))
ORDER BY "Prioridad" ASC, "UltimaEjecucion" DESC, "Fecha" DESC, "BajoDemanda" ASC
;