/*	*	*	*	*	*	*	*
 *	Reportes Bajo Demanda	*
 *	*	*	*	*	*	*	*/
SELECT   RDR.ID_CRON "IdCron"
        ,RDR.ID_REP "IdRep"
        ,RDR.NAME "NombreReporte"
        ,RC.PRIORITE "Prioridad"
        ,TO_CHAR(NVL(RDR.DATE_MODIFIED,RDR.DATE_CREATED),'DD/MM/YYYY HH24:MI:SS') "Fecha"
        ,TO_CHAR(RC.LAST_EXECUTION,'DD/MM/YYYY HH24:MI:SS') "UltimaEjecucion"
        ,RC.ACTIVE "Activo"
        ,RC.IN_PROGRESS "EnProceso"
        ,RC.MINUTES "Minutos"
        ,RC.HEURES "Horas"
        ,RC.JOURS "Dias"
        ,RC.MOIS "Mes"
        ,RC.JOUR_SEMAINE "DiaSemana"
        ,1 "BajoDemanda"
        ,TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') "SysDate"
FROM REP_DETALLE_REPORTE RDR
    INNER JOIN REP_CHRON RC ON RDR.ID_CRON = RC.ID_RAPPORT
WHERE   RC.IN_PROGRESS = 0
    AND RC.ACTIVE = 1
    AND RC.MINUTES IS NULL
    AND RC.HEURES IS NULL
    AND RC.JOURS IS NULL
    AND RC.MOIS IS NULL
    AND RC.JOUR_SEMAINE IS NULL
    AND TRUNC(NVL(RDR.DATE_MODIFIED,RDR.DATE_CREATED)) >= TRUNC(SYSDATE-1)
UNION
/*	*	*	*	*	*	*	*
 *	Reportes Programados	*
 *	*	*	*	*	*	*	*/
/* SIN UN DIA ESPECIFICO (UNICAMENTE HORAS Y/O MINUTOS) */
    SELECT   RDR.ID_CRON "IdCron"
            ,RDR.ID_REP "IdRep"
            ,RDR.NAME "NombreReporte"
            ,RC.PRIORITE "Prioridad"
            ,TO_CHAR(NVL(RDR.DATE_MODIFIED,RDR.DATE_CREATED),'DD/MM/YYYY HH24:MI:SS') "Fecha"
            ,TO_CHAR(RC.LAST_EXECUTION,'DD/MM/YYYY HH24:MI:SS') "UltimaEjecucion"
            ,RC.ACTIVE "Activo"
            ,RC.IN_PROGRESS "EnProceso"
            ,RC.MINUTES "Minutos"
            ,RC.HEURES "Horas"
            ,RC.JOURS "Dias"
            ,RC.MOIS "Mes"
            ,RC.JOUR_SEMAINE "DiaSemana"
            ,0 "BajoDemanda"
            ,TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') "SysDate"
    FROM REP_DETALLE_REPORTE RDR
        INNER JOIN REP_CHRON RC ON RDR.ID_CRON = RC.ID_RAPPORT
    WHERE   NVL(RC.IN_PROGRESS,0) = 0
        AND RC.ACTIVE = 1
        AND (RC.JOURS IS NULL AND RC.MOIS IS NULL AND RC.JOUR_SEMAINE IS NULL)
        AND (RC.MINUTES IS NOT NULL OR RC.HEURES IS NOT NULL)
        AND (
                TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MI'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.MINUTES,TO_CHAR(SYSDATE,'MI')))))
                OR
                TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MI'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.MINUTES,TO_CHAR(SYSDATE,'MI')))))
            )
        AND (
                TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'HH24'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.HEURES,TO_CHAR(SYSDATE,'HH24')))))
                OR
                TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'HH24'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.HEURES,TO_CHAR(SYSDATE,'HH24')))))
            )
UNION
/* CON UN DIA DE LA SEMANA ESPECIFICO CONFIGURADO */
    SELECT   RDR.ID_CRON "IdCron"
            ,RDR.ID_REP "IdRep"
            ,RDR.NAME "NombreReporte"
            ,RC.PRIORITE "Prioridad"
            ,TO_CHAR(NVL(RDR.DATE_MODIFIED,RDR.DATE_CREATED),'DD/MM/YYYY HH24:MI:SS') "Fecha"
            ,TO_CHAR(RC.LAST_EXECUTION,'DD/MM/YYYY HH24:MI:SS') "UltimaEjecucion"
            ,RC.ACTIVE "Activo"
            ,RC.IN_PROGRESS "EnProceso"
            ,RC.MINUTES "Minutos"
            ,RC.HEURES "Horas"
            ,RC.JOURS "Dias"
            ,RC.MOIS "Mes"
            ,RC.JOUR_SEMAINE "DiaSemana"
            ,0 "BajoDemanda"
            ,TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') "SysDate"
    FROM REP_DETALLE_REPORTE RDR
        INNER JOIN REP_CHRON RC ON RDR.ID_CRON = RC.ID_RAPPORT
    WHERE   NVL(RC.IN_PROGRESS,0) = 0
        AND RC.ACTIVE = 1
        AND RC.JOUR_SEMAINE IS NOT NULL
        AND RC.JOUR_SEMAINE = TO_CHAR(SYSDATE, 'D')
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MM'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.MOIS,TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MM')))))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'DD'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.JOURS,TO_CHAR(SYSDATE,'DD')))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'HH24'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.HEURES,TO_CHAR(SYSDATE,'HH24')))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MI'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.MINUTES,TO_CHAR(SYSDATE,'MI')))))
UNION
/* CON UN RANGO DE DÍAS A LA SEMANA CONFIGURADO */
    SELECT   RDR.ID_CRON "IdCron"
            ,RDR.ID_REP "IdRep"
            ,RDR.NAME "NombreReporte"
            ,RC.PRIORITE "Prioridad"
            ,TO_CHAR(NVL(RDR.DATE_MODIFIED,RDR.DATE_CREATED),'DD/MM/YYYY HH24:MI:SS') "Fecha"
            ,TO_CHAR(RC.LAST_EXECUTION,'DD/MM/YYYY HH24:MI:SS') "UltimaEjecucion"
            ,RC.ACTIVE "Activo"
            ,RC.IN_PROGRESS "EnProceso"
            ,RC.MINUTES "Minutos"
            ,RC.HEURES "Horas"
            ,RC.JOURS "Dias"
            ,RC.MOIS "Mes"
            ,RC.JOUR_SEMAINE "DiaSemana"
            ,0 "BajoDemanda"
            ,TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') "SysDate"
    FROM REP_DETALLE_REPORTE RDR
        INNER JOIN REP_CHRON RC ON RDR.ID_CRON = RC.ID_RAPPORT
    WHERE   NVL(RC.IN_PROGRESS,0) = 0
        AND RC.ACTIVE = 1
        AND RC.JOUR_SEMAINE IS NOT NULL
        AND TO_CHAR(SYSDATE, 'D') BETWEEN (SELECT COLUMN_VALUE VALOR FROM TABLE(SPLIT(RC.JOUR_SEMAINE,'-')) WHERE ROWNUM=1) AND (REPLACE(RC.JOUR_SEMAINE,(SELECT COLUMN_VALUE VALOR FROM TABLE(SPLIT(RC.JOUR_SEMAINE,'-')) WHERE ROWNUM=1)||'-',''))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MM'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.MOIS,TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MM')))))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'DD'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.JOURS,TO_CHAR(SYSDATE,'DD')))))
        AND (
                TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'HH24'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.HEURES,TO_CHAR(SYSDATE,'HH24')))))
                OR
                TO_CHAR(SYSDATE, 'HH24') BETWEEN (SELECT COLUMN_VALUE VALOR FROM TABLE(SPLIT(RC.HEURES,'-')) WHERE ROWNUM=1) AND (REPLACE(RC.HEURES,(SELECT COLUMN_VALUE VALOR FROM TABLE(SPLIT(RC.HEURES,'-')) WHERE ROWNUM=1)||'-',''))
            )
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MI'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.MINUTES,TO_CHAR(SYSDATE,'MI')))))
UNION
/* CON ALGUNOS DÍAS DE LA SEMANA CONFIGURADOS */
    SELECT   RDR.ID_CRON "IdCron"
            ,RDR.ID_REP "IdRep"
            ,RDR.NAME "NombreReporte"
            ,RC.PRIORITE "Prioridad"
            ,TO_CHAR(NVL(RDR.DATE_MODIFIED,RDR.DATE_CREATED),'DD/MM/YYYY HH24:MI:SS') "Fecha"
            ,TO_CHAR(RC.LAST_EXECUTION,'DD/MM/YYYY HH24:MI:SS') "UltimaEjecucion"
            ,RC.ACTIVE "Activo"
            ,RC.IN_PROGRESS "EnProceso"
            ,RC.MINUTES "Minutos"
            ,RC.HEURES "Horas"
            ,RC.JOURS "Dias"
            ,RC.MOIS "Mes"
            ,RC.JOUR_SEMAINE "DiaSemana"
            ,0 "BajoDemanda"
            ,TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') "SysDate"
    FROM REP_DETALLE_REPORTE RDR
        INNER JOIN REP_CHRON RC ON RDR.ID_CRON = RC.ID_RAPPORT
    WHERE   NVL(RC.IN_PROGRESS,0) = 0
        AND RC.ACTIVE = 1
        AND RC.JOUR_SEMAINE IS NOT NULL
        AND RC.JOUR_SEMAINE LIKE '%,%'
        AND (RC.JOUR_SEMAINE) LIKE '%' || TO_CHAR(SYSDATE, 'D') || '%'
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MM'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.MOIS,TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MM')))))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'DD'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.JOURS,TO_CHAR(SYSDATE,'DD')))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'HH24'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.HEURES,TO_CHAR(SYSDATE,'HH24')))))
        AND TO_CHAR(TO_NUMBER(TO_CHAR(SYSDATE,'MI'))) IN (SELECT COLUMN_VALUE FROM TABLE(SPLIT(NVL(RC.MINUTES,TO_CHAR(SYSDATE,'MI')))))
ORDER BY "Prioridad" ASC, "UltimaEjecucion" DESC, "Fecha" DESC, "BajoDemanda" ASC
;