//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsoleApp1.ventanillaunica {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'PolicyReference' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IReceptorEndpointBinding", Namespace="http://www.ventanillaunica.gob.mx/cove/ws/service/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComprobanteValorElectronicoBase))]
    public partial class RecibirCoveService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RecibirCoveOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecibirRelacionFacturasIAOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecibirRelacionFacturasNoIAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RecibirCoveService() {
            this.Url = global::ConsoleApp1.Properties.Settings.Default.ConsoleApp1_ventanillaunica_RecibirCoveService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RecibirCoveCompletedEventHandler RecibirCoveCompleted;
        
        /// <remarks/>
        public event RecibirRelacionFacturasIACompletedEventHandler RecibirRelacionFacturasIACompleted;
        
        /// <remarks/>
        public event RecibirRelacionFacturasNoIACompletedEventHandler RecibirRelacionFacturasNoIACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ventanillaunica.gob.mx/RecibirCove", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("solicitarRecibirCoveServicioResponse", Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
        public Acuse RecibirCove([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")] [System.Xml.Serialization.XmlArrayItemAttribute("comprobantes", IsNullable=false)] ComprobanteValorElectronico[] solicitarRecibirCoveServicio) {
            object[] results = this.Invoke("RecibirCove", new object[] {
                        solicitarRecibirCoveServicio});
            return ((Acuse)(results[0]));
        }
        
        /// <remarks/>
        public void RecibirCoveAsync(ComprobanteValorElectronico[] solicitarRecibirCoveServicio) {
            this.RecibirCoveAsync(solicitarRecibirCoveServicio, null);
        }
        
        /// <remarks/>
        public void RecibirCoveAsync(ComprobanteValorElectronico[] solicitarRecibirCoveServicio, object userState) {
            if ((this.RecibirCoveOperationCompleted == null)) {
                this.RecibirCoveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecibirCoveOperationCompleted);
            }
            this.InvokeAsync("RecibirCove", new object[] {
                        solicitarRecibirCoveServicio}, this.RecibirCoveOperationCompleted, userState);
        }
        
        private void OnRecibirCoveOperationCompleted(object arg) {
            if ((this.RecibirCoveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecibirCoveCompleted(this, new RecibirCoveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ventanillaunica.gob.mx/RecibirRelacionFacturasIA", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("solicitarRecibirRelacionFacturasIAServicioResponse", Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
        public Acuse RecibirRelacionFacturasIA([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")] [System.Xml.Serialization.XmlArrayItemAttribute("comprobantes", IsNullable=false)] ComprobanteValorElectronicoIA[] solicitarRecibirRelacionFacturasIAServicio) {
            object[] results = this.Invoke("RecibirRelacionFacturasIA", new object[] {
                        solicitarRecibirRelacionFacturasIAServicio});
            return ((Acuse)(results[0]));
        }
        
        /// <remarks/>
        public void RecibirRelacionFacturasIAAsync(ComprobanteValorElectronicoIA[] solicitarRecibirRelacionFacturasIAServicio) {
            this.RecibirRelacionFacturasIAAsync(solicitarRecibirRelacionFacturasIAServicio, null);
        }
        
        /// <remarks/>
        public void RecibirRelacionFacturasIAAsync(ComprobanteValorElectronicoIA[] solicitarRecibirRelacionFacturasIAServicio, object userState) {
            if ((this.RecibirRelacionFacturasIAOperationCompleted == null)) {
                this.RecibirRelacionFacturasIAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecibirRelacionFacturasIAOperationCompleted);
            }
            this.InvokeAsync("RecibirRelacionFacturasIA", new object[] {
                        solicitarRecibirRelacionFacturasIAServicio}, this.RecibirRelacionFacturasIAOperationCompleted, userState);
        }
        
        private void OnRecibirRelacionFacturasIAOperationCompleted(object arg) {
            if ((this.RecibirRelacionFacturasIACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecibirRelacionFacturasIACompleted(this, new RecibirRelacionFacturasIACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ventanillaunica.gob.mx/RecibirRelacionFacturasNoIA", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("solicitarRecibirRelacionFacturasNoIAServicioResponse", Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
        public Acuse RecibirRelacionFacturasNoIA([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")] [System.Xml.Serialization.XmlArrayItemAttribute("comprobantes", IsNullable=false)] ComprobanteValorElectronicoNoIA[] solicitarRecibirRelacionFacturasNoIAServicio) {
            object[] results = this.Invoke("RecibirRelacionFacturasNoIA", new object[] {
                        solicitarRecibirRelacionFacturasNoIAServicio});
            return ((Acuse)(results[0]));
        }
        
        /// <remarks/>
        public void RecibirRelacionFacturasNoIAAsync(ComprobanteValorElectronicoNoIA[] solicitarRecibirRelacionFacturasNoIAServicio) {
            this.RecibirRelacionFacturasNoIAAsync(solicitarRecibirRelacionFacturasNoIAServicio, null);
        }
        
        /// <remarks/>
        public void RecibirRelacionFacturasNoIAAsync(ComprobanteValorElectronicoNoIA[] solicitarRecibirRelacionFacturasNoIAServicio, object userState) {
            if ((this.RecibirRelacionFacturasNoIAOperationCompleted == null)) {
                this.RecibirRelacionFacturasNoIAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecibirRelacionFacturasNoIAOperationCompleted);
            }
            this.InvokeAsync("RecibirRelacionFacturasNoIA", new object[] {
                        solicitarRecibirRelacionFacturasNoIAServicio}, this.RecibirRelacionFacturasNoIAOperationCompleted, userState);
        }
        
        private void OnRecibirRelacionFacturasNoIAOperationCompleted(object arg) {
            if ((this.RecibirRelacionFacturasNoIACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecibirRelacionFacturasNoIACompleted(this, new RecibirRelacionFacturasNoIACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class ComprobanteValorElectronico : ComprobanteValorElectronicoBase {
        
        private string numeroFacturaOriginalField;
        
        private FacturaCove facturaField;
        
        private Emisor emisorField;
        
        private Destinatario destinatarioField;
        
        private Mercancia[] mercanciasField;
        
        /// <remarks/>
        public string numeroFacturaOriginal {
            get {
                return this.numeroFacturaOriginalField;
            }
            set {
                this.numeroFacturaOriginalField = value;
            }
        }
        
        /// <remarks/>
        public FacturaCove factura {
            get {
                return this.facturaField;
            }
            set {
                this.facturaField = value;
            }
        }
        
        /// <remarks/>
        public Emisor emisor {
            get {
                return this.emisorField;
            }
            set {
                this.emisorField = value;
            }
        }
        
        /// <remarks/>
        public Destinatario destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mercancias")]
        public Mercancia[] mercancias {
            get {
                return this.mercanciasField;
            }
            set {
                this.mercanciasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FacturaNoIA))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FacturaIA))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FacturaCove {
        
        private int certificadoOrigenField;
        
        private string numeroExportadorAutorizadoField;
        
        private int subdivisionField;
        
        /// <remarks/>
        public int certificadoOrigen {
            get {
                return this.certificadoOrigenField;
            }
            set {
                this.certificadoOrigenField = value;
            }
        }
        
        /// <remarks/>
        public string numeroExportadorAutorizado {
            get {
                return this.numeroExportadorAutorizadoField;
            }
            set {
                this.numeroExportadorAutorizadoField = value;
            }
        }
        
        /// <remarks/>
        public int subdivision {
            get {
                return this.subdivisionField;
            }
            set {
                this.subdivisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Acuse {
        
        private string numeroDeOperacionField;
        
        private System.DateTime horaRecepcionField;
        
        private string mensajeInformativoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string numeroDeOperacion {
            get {
                return this.numeroDeOperacionField;
            }
            set {
                this.numeroDeOperacionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime horaRecepcion {
            get {
                return this.horaRecepcionField;
            }
            set {
                this.horaRecepcionField = value;
            }
        }
        
        /// <remarks/>
        public string mensajeInformativo {
            get {
                return this.mensajeInformativoField;
            }
            set {
                this.mensajeInformativoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Domicilio {
        
        private string calleField;
        
        private string numeroExteriorField;
        
        private string numeroInteriorField;
        
        private string coloniaField;
        
        private string localidadField;
        
        private string municipioField;
        
        private string entidadFederativaField;
        
        private string paisField;
        
        private string codigoPostalField;
        
        /// <remarks/>
        public string calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        public string numeroExterior {
            get {
                return this.numeroExteriorField;
            }
            set {
                this.numeroExteriorField = value;
            }
        }
        
        /// <remarks/>
        public string numeroInterior {
            get {
                return this.numeroInteriorField;
            }
            set {
                this.numeroInteriorField = value;
            }
        }
        
        /// <remarks/>
        public string colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
            }
        }
        
        /// <remarks/>
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
        
        /// <remarks/>
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                this.municipioField = value;
            }
        }
        
        /// <remarks/>
        public string entidadFederativa {
            get {
                return this.entidadFederativaField;
            }
            set {
                this.entidadFederativaField = value;
            }
        }
        
        /// <remarks/>
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public string codigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Emisor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Destinatario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public abstract partial class Persona {
        
        private int tipoIdentificadorField;
        
        private string identificacionField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private string nombreField;
        
        private Domicilio domicilioField;
        
        /// <remarks/>
        public int tipoIdentificador {
            get {
                return this.tipoIdentificadorField;
            }
            set {
                this.tipoIdentificadorField = value;
            }
        }
        
        /// <remarks/>
        public string identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public Domicilio domicilio {
            get {
                return this.domicilioField;
            }
            set {
                this.domicilioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Emisor : Persona {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Destinatario : Persona {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class DescripcionMercancia {
        
        private string marcaField;
        
        private string modeloField;
        
        private string subModeloField;
        
        private string numeroSerieField;
        
        /// <remarks/>
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <remarks/>
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public string subModelo {
            get {
                return this.subModeloField;
            }
            set {
                this.subModeloField = value;
            }
        }
        
        /// <remarks/>
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Mercancia {
        
        private string descripcionGenericaField;
        
        private string claveUnidadMedidaField;
        
        private string tipoMonedaField;
        
        private decimal cantidadField;
        
        private decimal valorUnitarioField;
        
        private decimal valorTotalField;
        
        private decimal valorDolaresField;
        
        private DescripcionMercancia[] descripcionesEspecificasField;
        
        /// <remarks/>
        public string descripcionGenerica {
            get {
                return this.descripcionGenericaField;
            }
            set {
                this.descripcionGenericaField = value;
            }
        }
        
        /// <remarks/>
        public string claveUnidadMedida {
            get {
                return this.claveUnidadMedidaField;
            }
            set {
                this.claveUnidadMedidaField = value;
            }
        }
        
        /// <remarks/>
        public string tipoMoneda {
            get {
                return this.tipoMonedaField;
            }
            set {
                this.tipoMonedaField = value;
            }
        }
        
        /// <remarks/>
        public decimal cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        public decimal valorUnitario {
            get {
                return this.valorUnitarioField;
            }
            set {
                this.valorUnitarioField = value;
            }
        }
        
        /// <remarks/>
        public decimal valorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        public decimal valorDolares {
            get {
                return this.valorDolaresField;
            }
            set {
                this.valorDolaresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("descripcionesEspecificas")]
        public DescripcionMercancia[] descripcionesEspecificas {
            get {
                return this.descripcionesEspecificasField;
            }
            set {
                this.descripcionesEspecificasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FirmaElectronica {
        
        private byte[] certificadoField;
        
        private string cadenaOriginalField;
        
        private byte[] firmaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] certificado {
            get {
                return this.certificadoField;
            }
            set {
                this.certificadoField = value;
            }
        }
        
        /// <remarks/>
        public string cadenaOriginal {
            get {
                return this.cadenaOriginalField;
            }
            set {
                this.cadenaOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComprobanteValorElectronicoNoIA))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComprobanteValorElectronicoIA))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComprobanteValorElectronico))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public abstract partial class ComprobanteValorElectronicoBase {
        
        private string edocumentField;
        
        private TipoOperacion tipoOperacionField;
        
        private string[] patenteAduanalField;
        
        private System.DateTime fechaExpedicionField;
        
        private string observacionesField;
        
        private string[] rfcConsultaField;
        
        private int tipoFiguraField;
        
        private string correoElectronicoField;
        
        private FirmaElectronica firmaElectronicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("e-document", IsNullable=true)]
        public string edocument {
            get {
                return this.edocumentField;
            }
            set {
                this.edocumentField = value;
            }
        }
        
        /// <remarks/>
        public TipoOperacion tipoOperacion {
            get {
                return this.tipoOperacionField;
            }
            set {
                this.tipoOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patenteAduanal")]
        public string[] patenteAduanal {
            get {
                return this.patenteAduanalField;
            }
            set {
                this.patenteAduanalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fechaExpedicion {
            get {
                return this.fechaExpedicionField;
            }
            set {
                this.fechaExpedicionField = value;
            }
        }
        
        /// <remarks/>
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rfcConsulta")]
        public string[] rfcConsulta {
            get {
                return this.rfcConsultaField;
            }
            set {
                this.rfcConsultaField = value;
            }
        }
        
        /// <remarks/>
        public int tipoFigura {
            get {
                return this.tipoFiguraField;
            }
            set {
                this.tipoFiguraField = value;
            }
        }
        
        /// <remarks/>
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
            }
        }
        
        /// <remarks/>
        public FirmaElectronica firmaElectronica {
            get {
                return this.firmaElectronicaField;
            }
            set {
                this.firmaElectronicaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public enum TipoOperacion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TOCE.IMP")]
        TOCEIMP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TOCE.EXP")]
        TOCEEXP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class ComprobanteValorElectronicoNoIA : ComprobanteValorElectronicoBase {
        
        private string numeroRelacionFacturasField;
        
        private FacturaNoIA[] facturasField;
        
        /// <remarks/>
        public string numeroRelacionFacturas {
            get {
                return this.numeroRelacionFacturasField;
            }
            set {
                this.numeroRelacionFacturasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facturas")]
        public FacturaNoIA[] facturas {
            get {
                return this.facturasField;
            }
            set {
                this.facturasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FacturaNoIA : FacturaCove {
        
        private string numeroFacturaField;
        
        private Emisor emisorField;
        
        private Destinatario destinatarioField;
        
        private Mercancia[] mercanciasField;
        
        /// <remarks/>
        public string numeroFactura {
            get {
                return this.numeroFacturaField;
            }
            set {
                this.numeroFacturaField = value;
            }
        }
        
        /// <remarks/>
        public Emisor emisor {
            get {
                return this.emisorField;
            }
            set {
                this.emisorField = value;
            }
        }
        
        /// <remarks/>
        public Destinatario destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mercancias")]
        public Mercancia[] mercancias {
            get {
                return this.mercanciasField;
            }
            set {
                this.mercanciasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class ComprobanteValorElectronicoIA : ComprobanteValorElectronicoBase {
        
        private string numeroRelacionFacturasField;
        
        private Emisor emisorField;
        
        private Destinatario destinatarioField;
        
        private FacturaIA[] facturasField;
        
        /// <remarks/>
        public string numeroRelacionFacturas {
            get {
                return this.numeroRelacionFacturasField;
            }
            set {
                this.numeroRelacionFacturasField = value;
            }
        }
        
        /// <remarks/>
        public Emisor emisor {
            get {
                return this.emisorField;
            }
            set {
                this.emisorField = value;
            }
        }
        
        /// <remarks/>
        public Destinatario destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facturas")]
        public FacturaIA[] facturas {
            get {
                return this.facturasField;
            }
            set {
                this.facturasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FacturaIA : FacturaCove {
        
        private string numeroFacturaField;
        
        private Mercancia[] mercanciasField;
        
        /// <remarks/>
        public string numeroFactura {
            get {
                return this.numeroFacturaField;
            }
            set {
                this.numeroFacturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mercancias")]
        public Mercancia[] mercancias {
            get {
                return this.mercanciasField;
            }
            set {
                this.mercanciasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void RecibirCoveCompletedEventHandler(object sender, RecibirCoveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecibirCoveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecibirCoveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Acuse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Acuse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void RecibirRelacionFacturasIACompletedEventHandler(object sender, RecibirRelacionFacturasIACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecibirRelacionFacturasIACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecibirRelacionFacturasIACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Acuse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Acuse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void RecibirRelacionFacturasNoIACompletedEventHandler(object sender, RecibirRelacionFacturasNoIACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecibirRelacionFacturasNoIACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecibirRelacionFacturasNoIACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Acuse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Acuse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591