/* SC_RS_DIST.SPG_REP_REPORTES.P_DAT_REP_CLIENTE */
SELECT	 CLI.CLICLEF NUMERO
		,CLI.CLINOM NOMBRE
		,CLI.CLIRFC RFC
		,CLI.CLICODEPOSTAL CODIGO_POSTAL
		,CLI.CLISTATUS ESTATUS
		,CLI.CLIALIAS ALIAS
FROM	 ECLIENT CLI
WHERE	 CLI.CLICLEF	=	19810
;

/* SC_RS_DIST.SPG_REP_REPORTES.P_DAT_REP_DETALLE */
SELECT	 RDR.ID_CRON ID_CRON
		,TCRR.ID_REPORTE ID_REPORTE
		,TCRR.PROCESO_FUNCION PROCESO_FUNCION
		,RDR.NOMBRE NOMBRE
		,RDR.CLIENTE CLIENTE
		,RDR.CARPETA CARPETA
		,TCRR.SUBCARPETA SUBCARPETA
		,RDR.NOMBRE_ARCHIVO NOMBRE_ARCHIVO
		,TCRR.DIAS_EN_SERVIDOR DIAS_EN_SERVIDOR
FROM	 SC_RS_DIST.TB_REP_DETALLE_REPORTE RDR
	INNER	JOIN	SC_RS_DIST.TC_REP_REPORTES TCRR
		ON	RDR.ID_REPORTE	=	TCRR.ID_REPORTE
WHERE	RDR.ID_CRON	=	1
;

/* SC_RS_DIST.SPG_REP_REPORTES.P_DAT_REP_PARAMETRO */
SELECT	 RPR.ID_CRON ID_CRON
		,RPS.NUMERO_PARAMETRO NUMERO_PARAMETRO
		,RPS.VALOR VALOR
		,RPS.ETIQUETA_TEXTO ETIQUETA_TEXTO
		,TRP.DESCRIPCION DESCRIPCION
FROM	 SC_RS_DIST.TB_REP_REL_PARAMETROS_REPORTE RPR
	INNER	JOIN	SC_RS_DIST.TB_REP_PARAMETROS_SELECT RPS
		ON	RPR.ID_PARAMETRO_SELECT	=	RPS.ID_PARAMETRO_SELECT
	INNER	JOIN	SC_RS_DIST.TC_REP_PARAMETROS TRP
		ON	RPS.ID_PARAMETRO	=	TRP.ID_PARAMETRO
WHERE	RPR.ID_CRON	=	1
ORDER	BY
		NUMERO_PARAMETRO
;