 SELECT   'H'  
    , DECODE(ESAAI_M3_GENERAL.SGE_YCXCLEF, 1, 'I', 2, 'E') IMP_EXP  

    , RPAD(EFOLIOS.FOLFOLIO, 15, ' ') FOLIO 
    , TO_CHAR(ESAAI_M3_GENERAL.SGEFECHA_ENTRADA, 'DD-MM-YY') FECHA_ENTRADA  
    , RPAD(ESAAI_M3_GENERAL.SGE_REDCLEF, 4, ' ')  CLAVE_PED  
    , TO_CHAR(ESAAI_M3_GENERAL.SGEFECHA_PAGO, 'YY') || ESAAI_M3_GENERAL.SGEDOUCLEF || REPLACE(ESAAI_M3_GENERAL.SGEPEDNUMERO, '-') NUM_PEDIMENTO  
    , TO_CHAR(ESAAI_M3_GENERAL.SGE_TIPOCAMBIO, 'FM000000.0000') TIPO_CAMBIO  
    , TO_CHAR(ESAAI_M3_GENERAL.SGEFECHA_PAGO, 'DD-MM-YY') FECHA_PAGO  
    , ESAAI_M3_GENERAL.SGEDOUCLEF || ESAAI_M3_GENERAL.SGE_ADUANA_SECCION ADUANA_SEC  
    , TO_CHAR(DECODE(SGEFLETES + SGESEGUROS + SGEEMBALAJES + SGEOTROS_INC, 0, 1, DECODE(ESAAI_M3_GENERAL.SGEPRECIOPAGADO, 0, 0, ESAAI_M3_GENERAL.SGEVALORADUANA / ESAAI_M3_GENERAL.SGEPRECIOPAGADO)), 'FM0000.000000') PRECIO_PAGADO  
    , RPAD(DECODE(EFOLIOS.FOL_YTRCLEF, 1, 'MARITIMO ', 4, 'AEREO    ', 7, 'TERRESTRE', 6, 'FERROVIAR', 'OTROS    '), 16, ' ') TRANSITO  
    , ESAAI_M3_GENERAL.SGECLAVE   
    , 'IVA' IVA_GAL  
    , 'DTA' DTA_GAL  
    , 'ADV' ADV_GAL  
    , 'OTROS' OTROS_GAL  
    , TO_CHAR(NVL(SGEVALORDOLARES, 0), 'FM000000000.00') SGEVALORDOLARES  
    , TO_CHAR(NVL(DECODE(SGE_YCXCLEF, 2, 0, SGEVALORADUANA), 0), 'FM000000000000') SGEVALORADUANA  
    , TO_CHAR(NVL(SGEPRECIOPAGADO, 0), 'FM000000000000') SGEPRECIOPAGADO  

    , (SELECT TO_CHAR(NVL(SUM(FRFVALORAGREGADO), 0), 'FM000000000.00') 
       FROM EFACTURA_REF_FRA 
       , EFOLIO_FACTURA 
       WHERE FRFFACTURA = FOFCLEF 
       AND FOFFOLIO = EFOLIOS.FOLCLAVE 
       ) AS VALOR_AGREGADO_GAL   
    , 'D'  
    , SUBSTR(RPAD(GET_REF_FA_BOSCH_PEDIM3(SGECLAVE, NVL(REFREFERENCIA, FRDFRACCION), REF_TMETIPO, FRDFRACCION), 23, ' '), 1, 23) REFERENCIA    
    , ESAAI_M3_FACTURAS.SFA_PAYSAAIM3 PAIS_VENDEDOR  
    , EPAISES.PAYSAAIM3 PAIS_ORIGEN  
    , TO_CHAR(DECODE(FRF.FRFUNIDADES,0,1, FRF.FRFUNIDADES*DECODE(FRF.FRFUNIDADMEDIDA,18,100,17,10,11,1000,1)), 'FM000000000.0000') CDAD_UNIDADES  
    , TO_CHAR(FRF.FRFVALORCOMERCIAL*DECODE(FRF.FRFUNIDADES,0,DECODE(FOF.FOFDIVISA,'MXN', 1/SGE_TIPOCAMBIO, SFA_EQUIV_DIVISA),DECODE(FOF.FOFDIVISA, 'MXN' ,1/SGE_TIPOCAMBIO, SFA_EQUIV_DIVISA) / (FRF.FRFUNIDADES*DECODE(FRF.FRFUNIDADMEDIDA,18,100,17,10,11,1000,1))),'FM000000000.000000') COSTO_UNITARIO  
    , RPAD(DECODE(FRF.FRFUNIDADMEDIDA,17,6,18,6,11,6,FRF.FRFUNIDADMEDIDA), 4, ' ') MEDIDA  
    , VFRACCIONES_ARANCELARIAS.FRDFRACCION  FRACCION  

    , SPG_FRACCIONES_NICO.f_get_nico(EREFERENCIA.REFCLEF) NICO 

    , DECODE(SUBSTR(FRF.FRFTIPOADV, 1, 4), 'PROS', 'PS  ', NVL(SUBSTR(FRF.FRFTIPOADV, 1, 4), '    ')) TIPO_ADV   
    , NVL(TO_CHAR(SF_LOGIS_GET_TASA_ARANC(ESAAI_M3_GENERAL.SGECLAVE, VFRACCIONES_ARANCELARIAS.FRDFRACCION, EPAISES.PAYSAAIM3, FRF.FRFADV), 'FM000.00'), '      ') TASA_ARANC  

    ,  RPAD(DECODE(SUBSTR(FRF.FRFTIPOADV, 1, 4), 'TIGI', 'TIGI', 'TRAT', DECODE(DECODE(FRF.FRFPAISORI, 'N3', PAY_PROC.PAYCODPREFER, EPAISES.PAYCODPREFER), '1', 'TLCAN', 'LC', 'T-MEC', '2', 'TLCAN', '3', 'TLCEU', '14', 'TLCAELC', '23', 'T-MEC', '24', 'T-MEC', 'T-MEC'), 'PROS', 'PROSEC  ', 'OTROS'), 8, ' ') TRATADOS  

    , SUBSTR(RPAD(NVL(EDISTRIBUTEUR.DISPOSTECONTACT, EDISTRIBUTEUR.DISNUMERO), 8, ' '), 1, 8) NUM_DISTR  
    , SUBSTR(RPAD(NVL(DECODE(FOL_YFOCLEF, '8', FOF2.FOFFACTURA, FOF1.FOFFACTURA), ' '), 15, ' '), 1, 15) FAC_ORI  
    , RPAD(NVL(TO_CHAR(DECODE(FOL_YFOCLEF, '8', FOF2.FOFFECHA, FOF1.FOFFECHA), 'DD-MM-YY'), ' '), 8, ' ') FECHA_FACTURA  
    , DECODE(FOF.FOFVINCULACION, 0, 'NO', 'SI') VINC_PROV  
    , SUBSTR(RPAD(NVL(DECODE(FOL_YFOCLEF, '8', NVL(FRF2.FRFOBSERVACIONES, FOF2.FOFREFERENCIA), NVL(FRF1.FRFOBSERVACIONES, FOF1.FOFREFERENCIA)), ' '), 15, ' '), 1, 15) OC_ORI  
    , DECODE(COALESCE(FRF.FRFVALORAGREGADO, FRF1.FRFVALORAGREGADO, FRF2.FRFVALORAGREGADO), NULL, '0000000.000000000' 
       , TO_CHAR(COALESCE(FRF.FRFVALORAGREGADO, FRF1.FRFVALORAGREGADO, FRF2.FRFVALORAGREGADO) / DECODE(COALESCE(FRF.FRFUNIDADES, FRF1.FRFUNIDADES, FRF2.FRFUNIDADES),0,1, COALESCE( (FRF.FRFUNIDADES *DECODE(FRF.FRFUNIDADMEDIDA,18,100,17,10,11,1000,1)), (FRF1.FRFUNIDADES *DECODE(FRF1.FRFUNIDADMEDIDA,18,100,17,10,11,1000,1))  , ( FRF2.FRFUNIDADES * DECODE(FRF2.FRFUNIDADMEDIDA,18,100,17,10,11,1000,1))   )), 'FM0000000.000000000')   
     ) VALOR_AGREGADO   
    , SUBSTR(RPAD(ESAAI_M3_FACTURAS.SFANUMERO_FACTURA, 15, ' '), 1, 15) NUM_FACTURA  
    , TO_CHAR(SFAFECHA_FACTURACION, 'DD-MM-YY') AS FECHA_FACTURA_FX  
  ,RPAD(coalesce(LOGIS.GET_COVE(FOF.FOFCLEF), LOGIS.GET_COVE_RCO(DRC.DRC_RCOCLAVE),' ') ,15, ' ')   AS EDOCUMENT 
    , FOLFOLIO AS CLAVE_FAC  
    , RPAD(sf_logis_get_dato_adicional(ESAAI_M3_GENERAL.Sge_Cliclef, EFOLIOS.FOLCLAVE),7,' ') adicional  
    , TO_CHAR(ESAAI_M3_GENERAL.SGEFECHA_PAGO, 'YY') || '-' || ESAAI_M3_GENERAL.SGEDOUCLEF || '-' || ESAAI_M3_GENERAL.SGEPEDNUMERO NUM_PEDIMENTO_FX  
    , SUBSTR(ESAAI_M3_GENERAL.SGEPEDNUMERO,1,4) PATENTE  
    , EPAISES.PAYAES_ABREV_ISO2 PAIS_ORI_FX  
    , PAY_PROC.PAYAES_ABREV_ISO2 PAIS_DES_FX  
   FROM ESAAI_M3_GENERAL   
   , EPEDIMENTO   
   , EFOLIOS   
   , ESAAI_M3_FACTURAS   
   , EFACTURA_REF_FRA FRF 
   , VFRACCIONES_ARANCELARIAS   
   , EREFERENCIA   
   , EDISTRIBUTEUR   
   , EPAISES    
   , EFOLIO_FACTURA FOF 
   , ELIGA_FACTURA_REF_FRA LFRF1 
   , EFACTURA_REF_FRA FRF1 
   , EFOLIO_FACTURA FOF1 
   , ELIGA_FACTURA_REF_FRA LFRF2 
   , EFACTURA_REF_FRA FRF2 
   , EFOLIO_FACTURA FOF2 
   , EPAISES PAY_PROC   
               ,EDETRELACION_CONSOLIDADO DRC 

   , ESAAI_M3_PAGO SMP 

 WHERE ESAAI_M3_GENERAL.SGE_CLICLEF IN (11244, 11248)   

--If mi_sgeclave <> "" Then
      -- AND ESAAI_M3_GENERAL.SGECLAVE = " & mi_sgeclave & vbCrLf
--Else
      AND ESAAI_M3_GENERAL.SGEFECHA_PAGO BETWEEN TO_DATE('01/03/2024', 'mm/dd/yyyy') AND  TO_DATE('01/03/2024', 'mm/dd/yyyy') 
--End If

   AND ESAAI_M3_GENERAL.SGEFIRMA_ELECTRONICA IS NOT NULL   
   AND EPEDIMENTO.PEDNUMERO = ESAAI_M3_GENERAL.SGEPEDNUMERO   
   AND EPEDIMENTO.PEDANIO = ESAAI_M3_GENERAL.SGEANIO   
   AND EPEDIMENTO.PEDDOUANE = ESAAI_M3_GENERAL.SGEDOUCLEF   

   AND EXISTS (SELECT NULL FROM EAGENTDOUANE WHERE ADOPATENTE = SUBSTR(SGEPEDNUMERO, 1, 4))  

   AND EFOLIOS.FOLCLAVE = EPEDIMENTO.PEDFOLIO   
   AND EFOLIOS.FOL_CLICLEF IN (11244, 11248)   
   AND EFOLIOS.FOL_YCXCLEF =1  



   AND ESAAI_M3_FACTURAS.SFA_SGECLAVE = ESAAI_M3_GENERAL.SGECLAVE   
   AND EDISTRIBUTEUR.DISCLEF = ESAAI_M3_FACTURAS.SFADISCLEF   
   AND FRF.FRFFACTURA = ESAAI_M3_FACTURAS.SFA_FOFCLEF   


   AND EREFERENCIA.REFCLEF(+) = FRF.FRFREFERENCIA   
   AND VFRACCIONES_ARANCELARIAS.FRACLAVE = FRF.FRFFRACCION   
   AND VFRACCIONES_ARANCELARIAS.FRDFECHAVIG <= DECODE( NVL(ESAAI_M3_GENERAL.SGE_REDCLEF_RECTIF, ESAAI_M3_GENERAL.SGE_REDCLEF), 'F4', ESAAI_M3_GENERAL.SGEFECHA_PAGO, 'F5', ESAAI_M3_GENERAL.SGEFECHA_PAGO, ESAAI_M3_GENERAL.SGEFECHA_ENTRADA)   
   AND NVL(VFRACCIONES_ARANCELARIAS.FRDFECHAFIN, DECODE( NVL(ESAAI_M3_GENERAL.SGE_REDCLEF_RECTIF, ESAAI_M3_GENERAL.SGE_REDCLEF), 'F4', ESAAI_M3_GENERAL.SGEFECHA_PAGO, 'F5', ESAAI_M3_GENERAL.SGEFECHA_PAGO, ESAAI_M3_GENERAL.SGEFECHA_ENTRADA)) >= DECODE( NVL(ESAAI_M3_GENERAL.SGE_REDCLEF_RECTIF, ESAAI_M3_GENERAL.SGE_REDCLEF), 'F4', ESAAI_M3_GENERAL.SGEFECHA_PAGO, 'F5', ESAAI_M3_GENERAL.SGEFECHA_PAGO, ESAAI_M3_GENERAL.SGEFECHA_ENTRADA)  
   AND VFRACCIONES_ARANCELARIAS.FRAFECHAVIG <= DECODE( NVL(ESAAI_M3_GENERAL.SGE_REDCLEF_RECTIF, ESAAI_M3_GENERAL.SGE_REDCLEF), 'F4', ESAAI_M3_GENERAL.SGEFECHA_PAGO, 'F5', ESAAI_M3_GENERAL.SGEFECHA_PAGO, ESAAI_M3_GENERAL.SGEFECHA_ENTRADA)  
   AND NVL(VFRACCIONES_ARANCELARIAS.FRAFECHAFIN, DECODE( NVL(ESAAI_M3_GENERAL.SGE_REDCLEF_RECTIF, ESAAI_M3_GENERAL.SGE_REDCLEF), 'F4', ESAAI_M3_GENERAL.SGEFECHA_PAGO, 'F5', ESAAI_M3_GENERAL.SGEFECHA_PAGO, ESAAI_M3_GENERAL.SGEFECHA_ENTRADA)) >= DECODE( NVL(ESAAI_M3_GENERAL.SGE_REDCLEF_RECTIF, ESAAI_M3_GENERAL.SGE_REDCLEF), 'F4', ESAAI_M3_GENERAL.SGEFECHA_PAGO, 'F5', ESAAI_M3_GENERAL.SGEFECHA_PAGO, ESAAI_M3_GENERAL.SGEFECHA_ENTRADA)  
   AND EPAISES.PAYCLEF = FRF.FRFPAISORI   
   AND FOF.FOFCLEF(+) = ESAAI_M3_FACTURAS.SFA_FOFCLEF   
   AND PAY_PROC.PAYCLEF(+) = FOF.FOF_PAYCLEF_PROC   
   AND LFRF1.LFRF_FRFCLEFDEST(+) = FRF.FRFCLEF 
   AND FRF1.FRFCLEF(+) = LFRF1.LFRF_FRFCLEFORI 
   AND FOF1.FOFCLEF(+) = FRF1.FRFFACTURA 
   AND LFRF2.LFRF_FRFCLEFDEST(+) = LFRF1.LFRF_FRFCLEFORI 
   AND FRF2.FRFCLEF(+) = LFRF2.LFRF_FRFCLEFORI 
   AND FOF2.FOFCLEF(+) = FRF2.FRFFACTURA 


               AND DRC.DRC_FOLCLAVE(+) = FOF1.FOFFOLIO 

   AND SMP.SMP_SGECLAVE = ESAAI_M3_GENERAL.SGECLAVE 
   AND SMP.SMP_FECHA_PAGO IS NOT NULL 
